### ISSUE TITLE
Color support

### ISSUE THREAD

**Issue by vigo** [Hipo/hst#4]
My history output has some colors and few more things:

<img width="1217" alt="screen shot 2015-10-13 at 13 30 50" src="https://cloud.githubusercontent.com/assets/82952/10452582/a5d660a8-71ae-11e5-9c14-01ee519d6cd6.png">

When I tried this lovely tool, color codes made the output a bit nasty :)

<img width="1217" alt="screen shot 2015-10-13 at 13 30 07" src="https://cloud.githubusercontent.com/assets/82952/10452563/8702840e-71ae-11e5-8cb0-14090f5f14bf.png">

I'd like to let you guys know this :)

**Comment by ybrs** [comment]
@vigo thank you, are you using bash or zsh or something ? my history output is 

```
45651  git pull origin production
45652  pyc `pwd`
45653  git reset
```

its pretty easy to add a parser but im not sure how you made that coloured history :)

**Comment by vigo** [comment]
Here is my funky format (I use BASH):

`export HISTTIMEFORMAT="[$(tput setaf 2)%F %T$(tput sgr0)]: "`

must unset `HISTTIMEFORMAT` shell variable before calling.

``` python
class HistoryLoader(Loader):
    def load(self):
        from subprocess import Popen, PIPE, STDOUT
        shell_command = 'bash -i -c "unset HISTTIMEFORMAT; history -r; history"'
    :
    :
```

Due to missing tests, I couldn't test the code. Can you please check it?

**Comment by ybrs** [comment]
great :) i tested this and works as expected. can you open a pull request for this ? or i can just push.

for missing tests, i really couldnt find a good way to test an curses application, other than just testing some simple functions there is not a good way to unit test it. but if you have any suggestions please let me know.

**Comment by vigo** [comment]
Please push it :) Well, I'll try to find out how to test it. Love to report if anything happens. I have lots of things with history all the time. Thats why I use `.inputrc`. I hope this nifty tool will save my days :)

**Comment by ybrs** [comment]
thanks for kind words. hope it will work for you too. 

and thanks for the patch, i pushed your changes and uploaded to pypi, closing the issue. please don't hesitate to open an issue if you see any problems or anything pops in your mind.
